"""Integration-layer exports for embodied execution."""

from roboclaw.embodied.execution.integration.adapters import (
    AdapterBinding,
    AdapterCompatibilitySpec,
    AdapterHealthMode,
    AdapterLifecycleContract,
    AdapterOperation,
    AdapterRegistry,
    CompatibilityComponent,
    DEFAULT_ADAPTER_COMPATIBILITY,
    DEFAULT_ADAPTER_LIFECYCLE,
    DegradedModeSpec,
    DependencyKind,
    DependencySpec,
    EmbodiedAdapter,
    ErrorCategory,
    ErrorCodeSpec,
    OperationTimeout,
    TimeoutPolicy,
    VersionConstraint,
)
from roboclaw.embodied.execution.integration.bridges import (
    ARM_HAND_BRIDGE,
    BridgeDomain,
    BridgeKind,
    BridgeRegistry,
    ControlSurfaceSpec,
    DEFAULT_DOMAIN_BRIDGES,
    DRONE_BRIDGE,
    DomainBridgeContract,
    HUMANOID_WHOLE_BODY_BRIDGE,
    MOBILE_BASE_FLEET_BRIDGE,
    ObservationSurfaceSpec,
    SIMULATOR_BRIDGE,
)
from roboclaw.embodied.execution.integration.carriers import ExecutionTarget
from roboclaw.embodied.execution.integration.transports import (
    Ros2ActionSpec,
    Ros2InterfaceBundle,
    Ros2ServiceSpec,
    Ros2TopicSpec,
    build_standard_ros2_contract,
    canonical_ros2_namespace,
)

__all__ = [
    "AdapterBinding",
    "AdapterCompatibilitySpec",
    "AdapterHealthMode",
    "AdapterLifecycleContract",
    "AdapterOperation",
    "AdapterRegistry",
    "ARM_HAND_BRIDGE",
    "BridgeDomain",
    "BridgeKind",
    "BridgeRegistry",
    "CompatibilityComponent",
    "ControlSurfaceSpec",
    "DEFAULT_ADAPTER_COMPATIBILITY",
    "DEFAULT_ADAPTER_LIFECYCLE",
    "DEFAULT_DOMAIN_BRIDGES",
    "DegradedModeSpec",
    "DependencyKind",
    "DependencySpec",
    "DRONE_BRIDGE",
    "DomainBridgeContract",
    "EmbodiedAdapter",
    "ErrorCategory",
    "ErrorCodeSpec",
    "ExecutionTarget",
    "HUMANOID_WHOLE_BODY_BRIDGE",
    "MOBILE_BASE_FLEET_BRIDGE",
    "ObservationSurfaceSpec",
    "OperationTimeout",
    "Ros2ActionSpec",
    "Ros2InterfaceBundle",
    "Ros2ServiceSpec",
    "Ros2TopicSpec",
    "SIMULATOR_BRIDGE",
    "TimeoutPolicy",
    "VersionConstraint",
    "build_standard_ros2_contract",
    "canonical_ros2_namespace",
]
