"""Adapter exports."""

from roboclaw.embodied.execution.integration.adapters.model import (
    AdapterBinding,
    AdapterCompatibilitySpec,
    AdapterHealthMode,
    AdapterLifecycleContract,
    AdapterOperation,
    AdapterOperationResult,
    AdapterStateSnapshot,
    CompatibilityCheckItem,
    CompatibilityCheckResult,
    CompatibilityComponent,
    DEFAULT_ADAPTER_LIFECYCLE,
    DEFAULT_ADAPTER_COMPATIBILITY,
    DebugSnapshotResult,
    DegradedModeSpec,
    DependencyCheckItem,
    DependencyCheckResult,
    DependencyKind,
    DependencySpec,
    EnvironmentProbeResult,
    ErrorCategory,
    ErrorCodeSpec,
    HealthReport,
    OperationTimeout,
    PrimitiveExecutionResult,
    ReadinessReport,
    SensorCaptureResult,
    TimeoutPolicy,
    VersionConstraint,
)
from roboclaw.embodied.execution.integration.adapters.protocols import EmbodiedAdapter
from roboclaw.embodied.execution.integration.adapters.registry import AdapterRegistry

__all__ = [
    "AdapterBinding",
    "AdapterCompatibilitySpec",
    "AdapterHealthMode",
    "AdapterLifecycleContract",
    "AdapterOperation",
    "AdapterOperationResult",
    "AdapterRegistry",
    "AdapterStateSnapshot",
    "CompatibilityCheckItem",
    "CompatibilityCheckResult",
    "CompatibilityComponent",
    "DEFAULT_ADAPTER_COMPATIBILITY",
    "DEFAULT_ADAPTER_LIFECYCLE",
    "DebugSnapshotResult",
    "DegradedModeSpec",
    "DependencyCheckItem",
    "DependencyCheckResult",
    "DependencyKind",
    "DependencySpec",
    "EmbodiedAdapter",
    "EnvironmentProbeResult",
    "ErrorCategory",
    "ErrorCodeSpec",
    "HealthReport",
    "OperationTimeout",
    "PrimitiveExecutionResult",
    "ReadinessReport",
    "SensorCaptureResult",
    "TimeoutPolicy",
    "VersionConstraint",
]
